# Step 1: Build the Vite.js project
FROM node:18 AS build

WORKDIR /app

COPY ../frontend/package.json ../frontend/package-lock.json ./

RUN npm install

COPY ../frontend ./ 

RUN echo "VITE_APP_API_URL=/api/" > .env && \
    echo "VITE_APP_ENV=production" >> .env

RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html


RUN rm /etc/nginx/conf.d/default.conf
COPY ../scripts/nginx.conf /etc/nginx/conf.d/default.conf
COPY ../Certificate /etc/nginx/certs

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
