# Generated by Django 4.1.2 on 2022-11-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRetest',
        ),
    ]
