# Generated by Django 4.1.2 on 2022-11-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_delete_projectretest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retestcount', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
