# Generated by Django 4.1.2 on 2022-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectretest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='testingtype',
            field=models.CharField(default='White Box', max_length=100),
        ),
    ]
