# Generated by Django 4.1.2 on 2022-11-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_testingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectexception',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
