# Generated by Django 4.1.2 on 2022-11-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '__first__'),
        ('project', '0006_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='companyname',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
