# Generated by Django 4.2.15 on 2024-11-23 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, validators=[utils.validators.xss_validator])),
                ('projecttype', models.CharField(default=None, max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('testingtype', models.CharField(default='White Box', max_length=100)),
                ('projectexception', models.TextField(blank=True, null=True, validators=[utils.validators.xss_validator])),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Delay', 'Delay'), ('Completed', 'Completed')], max_length=20)),
                ('companyname', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company')),
                ('owner', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerabilityname', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('vulnerabilityseverity', models.CharField(max_length=300, null=True)),
                ('cvssscore', models.FloatField(blank=True, null=True)),
                ('cvssvector', models.CharField(default=None, max_length=300, null=True)),
                ('status', models.CharField(choices=[('Vulnerable', 'Vulnerable'), ('Confirm Fixed', 'Confirm Fixed'), ('Accepted Risk', 'Accepted Risk')], default='Vulnerable', max_length=20)),
                ('vulnerabilitydescription', models.TextField(blank=True, null=True, validators=[utils.validators.xss_validator])),
                ('POC', models.TextField(blank=True, default=None, null=True, validators=[utils.validators.xss_validator])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('vulnerabilitysolution', models.TextField(blank=True, null=True, validators=[utils.validators.xss_validator])),
                ('vulnerabilityreferlnk', models.TextField(blank=True, null=True, validators=[utils.validators.xss_validator])),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerability_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerability_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'unique_together': {('project', 'vulnerabilityname')},
            },
        ),
        migrations.CreateModel(
            name='Vulnerableinstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('Parameter', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('Vulnerable', 'Vulnerable'), ('Confirm Fixed', 'Confirm Fixed'), ('Accepted Risk', 'Accepted Risk')], default='Vulnerable', max_length=20)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('vulnerabilityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='project.vulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Delay', 'Delay'), ('Completed', 'Completed')], max_length=20)),
                ('owner', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='PrjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'unique_together': {('project', 'scope')},
            },
        ),
    ]
