# Generated by Django 4.2.20 on 2025-05-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_vulnerability_cwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='standard',
            field=models.JSONField(default=list),
        ),
    ]
