# Generated by Django 3.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_vulnerability_fixed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectretest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectretest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectretest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]