# Generated by Django 4.2.20 on 2025-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_projectretest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Reason why the project is on hold', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Delay', 'Delay'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
