# Generated by Django 4.2.20 on 2025-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_hold_reason_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='testingtype',
            field=models.CharField(blank=True, default='White Box', max_length=100, null=True),
        ),
    ]
