# Generated by Django 4.2.20 on 2025-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvitation',
            name='token_type',
            field=models.CharField(choices=[('invitation', 'Invitation Token'), ('password_reset', 'Password Reset Token')], default='invitation', max_length=20),
        ),
    ]
