name: Frontend Test and Build

on:
  push:
    branches: [ "main" ,'API']
  pull_request:
    branches: [ "main" ,'API']

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 21, 22]
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Create .env file
      - name: Create .env file
        run: |
          echo "VITE_APP_API_URL=/api/" > frontend/.env
          echo "VITE_APP_ENV=production" >> frontend/.env

      # Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Build the frontend
        working-directory: frontend
        run: npm run build

      # Upload build artifact (optional)
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-node-${{ matrix.node-version }}-${{ github.run_number }}
          path: frontend/dist
